# Generated by Django 4.0.5 on 2022-06-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0006_profesor_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='dni',
        ),
    ]
