# Generated by Django 4.0.5 on 2022-06-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0011_accesorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AlterModelOptions(
            name='accesorio',
            options={'verbose_name_plural': 'Profesores'},
        ),
    ]
