# Generated by Django 4.0.5 on 2022-07-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0013_delete_entregable_alter_accesorio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
