# Generated by Django 4.0.5 on 2022-07-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0029_alter_vehiculo_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
